version: '3.1'

services:
  gateway:
    build: .
    command: yarn start:dev
    restart: always
    ports:
      - 4000:3000
    volumes: 
      - ./:/usr/src/app
    networks:
      - djarn

  cache:
    image: redis
    restart: always
    # ports:
    #   - 6379:6379
    networks:
      - djarn

networks:
   djarn:
     external: true
